/**
 * The Meta deduplication contract, in one place.
 *
 * THIS MODULE IS ISOMORPHIC AND MUST STAY THAT WAY. It is imported by the browser Pixel
 * (`src/lib/meta-pixel.ts`) AND by the server Conversions API module
 * (`src/server/meta-capi.ts`), because the two halves have to agree on the `event_id` of a
 * given action or Meta counts it twice. Two copies of this rule would drift, and the day
 * they drift is the day reported conversions silently inflate.
 *
 * It therefore touches no `window`, no `import.meta.env`, no `process.env`, no secret and
 * no network. Adding any of those to this file breaks one of the two importers — the
 * browser one at build time, or the server one by pulling a browser global into a Vercel
 * Function. There is a test that asserts exactly this (`meta-events.test.ts`).
 *
 * WHY event_id IS DERIVED, NOT RANDOM
 *
 * Meta deduplicates on the pair (`event_name`, `event_id`). For a browser event and a
 * server event to collapse into one conversion, both must present the same string. A
 * random id works only if the browser can hand it to the server — and the whole reason
 * server-side forwarding exists is that the browser is frequently blocked, so it cannot be
 * relied on to hand anything over. The ids below are therefore DERIVED from the identity
 * of the action itself, so both sides can compute the same value independently, and the
 * server can still emit a correctly-deduplicating event when the browser sent nothing at
 * all.
 *
 * Events with no server counterpart get a random id. That is not laziness: a random id
 * deduplicates against nothing, which is the correct behaviour for an event that exists in
 * exactly one place, and it stops two genuinely separate actions being collapsed.
 */

/** The Meta standard events this product raises. Nothing custom, nothing else. */
export type MetaEventName =
'PageView' |
'ViewContent' |
'InitiateCheckout' |
'CompleteRegistration' |
'Purchase';

/**
 * Purchase — SERVER ONLY today.
 *
 * The event id is the Stripe Checkout Session id (`cs_...`) verbatim. It is unique per
 * purchase, it is generated by Stripe rather than by either of our two halves, and it is
 * present on `checkout.session.completed`, so a future browser purchase event could adopt
 * it without changing anything here.
 *
 * There is deliberately no browser `Purchase` (see src/TRACKING.md): payment success is
 * only known server-side, and a browser event inflates on refunds, failed cards and
 * redirect drop-off. So this currently deduplicates against nothing — the plumbing is
 * correct in advance rather than retrofitted after the numbers have already been wrong.
 */
export function purchaseEventId(checkoutSessionId: string): string {
  return checkoutSessionId.trim();
}

/**
 * CompleteRegistration — BROWSER ONLY today, but built to dedupe.
 *
 * Keyed on the SHA-256 of the normalised email rather than the Supabase user id, because
 * the user id is the one thing the browser does not always have: a magic-link signup
 * returns no user until the link is clicked, so `trackSignUpCompleted` fires with
 * `userId` undefined. The email hash is known to both halves on every signup path
 * (password, magic link and Google), which is what makes this rule usable by a future
 * server-side signup event without a second, contradictory keying scheme.
 *
 * Consequence, stated rather than discovered later: one registration per email address
 * per Meta dedup window. Somebody who deletes their account and signs up again with the
 * same address inside that window is counted once. That is the intended reading of
 * "registration" anyway.
 *
 * Returns null when there is no hash — which is what happens when advertising consent was
 * refused and `em_sha256` was therefore never computed. A registration with no stable id
 * must not be given a random one: a random id would look deduplicable and would not be.
 */
export function registrationEventId(emailSha256: string | null | undefined): string | null {
  if (!emailSha256) return null;
  return `signup.${emailSha256}`;
}

/**
 * An id for an event that exists in exactly one place.
 *
 * Uses `crypto.randomUUID` where available (every browser and runtime this ships to) and
 * falls back to a time-plus-entropy string, so a jsdom test or an odd runtime cannot make
 * this throw inside a tracking call and take a page render down with it.
 */
export function randomEventId(): string {
  const c = typeof crypto !== 'undefined' ? crypto : undefined;
  if (c && typeof c.randomUUID === 'function') return c.randomUUID();
  return `e.${Date.now().toString(36)}.${Math.random().toString(36).slice(2, 12)}`;
}

/**
 * Meta's `fbc` click identifier, rebuilt from a raw `fbclid`.
 *
 * FORMAT: `fb.<subdomainIndex>.<creationTimeMs>.<fbclid>`
 *
 * `subdomainIndex` is 1. It describes which part of the hostname the `_fbc` cookie was
 * written on, counting from the public suffix: `xyz` = 0, `batchlabel.xyz` = 1,
 * `www.batchlabel.xyz` = 2. Meta's own documentation for reconstructing `fbc` from a
 * query parameter specifies 1, and the Pixel writes 1 for a cookie on the registrable
 * domain, so 1 is what keeps a reconstructed value byte-identical to a real one.
 *
 * `creationTimeMs` is THE TIME THE fbclid WAS OBSERVED, in unix MILLISECONDS — not the
 * time of the conversion. This is the part that is easy to get wrong and expensive to get
 * wrong. The Pixel writes `_fbc` at the moment the ad click lands, so the timestamp inside
 * a real cookie is the click time. If the server substituted the purchase time, the same
 * click would produce two different `fbc` strings — one in the browser's cookie, one in the
 * server event — and Meta matches on the whole string. The browser and server halves would
 * then look like two different clicks instead of one.
 *
 * Batchlabel captures the click time already: `first_seen_at` on the first-touch
 * attribution record (`src/lib/attribution.ts`), which is written in the same tick that
 * `fbclid` is read off the URL and is carried into Stripe Checkout metadata specifically so
 * this function can be called from the webhook.
 *
 * `observedAtMs` is null/unparseable only when the stored record predates that capture or
 * was corrupted. The caller decides what to pass as a fallback; passing the conversion
 * time is a documented, lower-quality option (Meta permits reconstructing with the time
 * the identifier was observed), and passing null yields null rather than a fabricated
 * timestamp.
 */
export function buildFbc(
fbclid: string | null | undefined,
observedAtMs: number | null | undefined)
: string | null {
  const id = typeof fbclid === 'string' ? fbclid.trim() : '';
  if (!id) return null;
  if (typeof observedAtMs !== 'number' || !Number.isFinite(observedAtMs) || observedAtMs <= 0) {
    return null;
  }
  return `fb.1.${Math.floor(observedAtMs)}.${id}`;
}

/** ISO 8601 to unix milliseconds, or null when it is absent or unparseable. */
export function isoToUnixMs(iso: string | null | undefined): number | null {
  if (typeof iso !== 'string' || !iso.trim()) return null;
  const ms = Date.parse(iso);
  return Number.isFinite(ms) ? ms : null;
}

/**
 * Is this a plausible `_fbp` cookie value?
 *
 * `fb.<subdomainIndex>.<creationTimeMs>.<random>` where every segment is digits. Used to
 * validate a value that arrived from a browser before it is written into Stripe metadata
 * and later sent to Meta — a request body is not a trustworthy source of anything, and an
 * unvalidated string here would let a caller put arbitrary text into our Meta events.
 */
export function isValidFbp(value: unknown): value is string {
  return typeof value === 'string' && /^fb\.\d+\.\d+\.\d+$/.test(value.trim());
}

/**
 * Is this a plausible `_fbc` cookie value?
 *
 * Same shape, but the final segment is the fbclid, which is an opaque URL-safe token
 * rather than digits. Length-capped so a hostile caller cannot push a Stripe metadata
 * value over its 500-character limit and turn a paid checkout into a 400.
 */
export function isValidFbc(value: unknown): value is string {
  return typeof value === 'string' && /^fb\.\d+\.\d+\.[A-Za-z0-9_-]{1,400}$/.test(value.trim());
}
